services:
  - type: web
    name: my-site-blog
    runtime: python
    repo: https://github.com/aaab0914/my_site
    plan: free
    branch: main
    buildCommand: |
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput
    startCommand: gunicorn my_site.wsgi:application -b 0.0.0.0:8000 --workers 3
    envVars:
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: my-site-db
          property: connectionString

databases:
  - name: my-site-db
    plan: free